name: perf_tool
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: devoncarew <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  intl: ^0.15.0
  logging: ^0.11.0
  vm_service_lib: ^0.3.5

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: any

web:
  compiler:
    debug: dartdevc

transformers:
- dart_to_js_script_rewriter
